from ..op import OpDetails


class BaseRecorder:
    async def start(self): ...
    async def end(self): ...
    async def last_events_id(self): ...
    async def save_events(self, name: str, payload: dict, *, unknown=False): ...
    async def save_packets(self, op_code: str, details: OpDetails): ...
